ingress: 
  globalStaticIpName: landing-production
  hosts:
    - sourced.tech
    - www.sourced.tech
nodeSelector:
  cloud.google.com/gke-nodepool: default-pool
affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
         matchExpressions:
          - key: app
            operator: In
            values:
         #if the chart name is changed or a nameOverride is used, this value has to be changed to the new name.
                - landing
        topologyKey: kubernetes.io/hostname
image:
  registry: docker.io/srcd
