language: go

go:
  - 1.8
  - tip

sudo: required

services:
  - docker

cache:
  directories:
    - node_modules

env:
  global:
    - DOCKER_REGISTRY: quay.io
    - DOCKER_ORG: quay.io/srcd

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 8
  - nvm use 8
  - npm install -g yarn
  - npm rebuild node-sass
  - go get -u -v -t ./api/...

script:
  - go test ./api/...
  - make build

before_deploy:
  - make packages
  - make package-hugo-generated

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: build/*.tar.gz
  skip_cleanup: true
  on:
    tags: true
    go: 1.8

after_deploy:
  - make docker-push
