FROM node:6.10-alpine

ENV PORT 3000
ENV SLACK_API_TOKEN ***REMOVED***
ENV SLACK_SUBDOMAIN sourced-community

RUN mkdir -p /srv

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh

RUN git clone https://github.com/rauchg/slackin.git /srv/www

WORKDIR /srv/www

RUN npm install --unsafe-perm

EXPOSE 3000

CMD ./bin/slackin --port $PORT $SLACK_SUBDOMAIN $SLACK_API_TOKEN
