FROM node:8-alpine

ENV SLACK_SUBDOMAIN sourced-community

RUN mkdir -p /srv

RUN apk update && apk upgrade && \
    apk add --no-cache git openssh

RUN git clone https://github.com/rauchg/slackin.git /srv/www

WORKDIR /srv/www

RUN git checkout 0.13.1

RUN npm install --unsafe-perm

EXPOSE 3000

CMD ./bin/slackin --cors --port 3000 $SLACK_SUBDOMAIN $SLACK_API_TOKEN
