FROM node:8-alpine

ENV SLACK_SUBDOMAIN sourced-community
ENV SLACKIN_BIND_PORT 3000
ENV SLACKIN_BIND_HOST 0.0.0.0

RUN mkdir -p /srv

RUN apk update && apk upgrade && \
    apk add --no-cache git openssh

RUN git clone https://github.com/rauchg/slackin.git /srv/www

WORKDIR /srv/www

RUN git checkout 0.13.1

RUN npm install --unsafe-perm

EXPOSE $SLACKIN_BIND_PORT

CMD ./bin/slackin --cors --hostname $SLACKIN_BIND_HOST --port $SLACKIN_BIND_PORT $SLACK_SUBDOMAIN $SLACK_API_TOKEN
